### ISSUE TITLE
Add random methods in the library

### ISSUE THREAD

**Issue by Gpx** [travelperk/fabricator#19]
You don't have to rely on `faker` or other external libraries to get fake data. You should be able to get all the methods you need within fabricator.

**Comment by robmosca** [comment]
Closing this issue as it is outstanding for a long time.

The suggestion is indeed useful.

We also have a problem of Heisen tests when random values are duplicated within the pool. We would need to find a way to specify that an attribute that is randomly generated should have unique values within the pool.
